//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webstoreEntities : DbContext
    {
        public webstoreEntities()
            : base("name=webstoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCategories> tblCategories { get; set; }
        public virtual DbSet<tblProducts> tblProducts { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
        public virtual DbSet<tblCountry> tblCountry { get; set; }
        public virtual DbSet<tblComunas> tblComunas { get; set; }
        public virtual DbSet<tblProvincias> tblProvincias { get; set; }
        public virtual DbSet<tblRegiones> tblRegiones { get; set; }
        public virtual DbSet<tblFamily> tblFamily { get; set; }
        public virtual DbSet<tblModel> tblModel { get; set; }
        public virtual DbSet<tblModelDetail> tblModelDetail { get; set; }
        public virtual DbSet<tblCategoryRelation> tblCategoryRelation { get; set; }
        public virtual DbSet<tblBrand> tblBrand { get; set; }
        public virtual DbSet<tblOffert> tblOffert { get; set; }
        public virtual DbSet<tblOffertTime> tblOffertTime { get; set; }
        public virtual DbSet<tblImg> tblImg { get; set; }
        public virtual DbSet<tblRelBrand> tblRelBrand { get; set; }
        public virtual DbSet<tblFicha> tblFicha { get; set; }
    }
}
