//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webstoreEntities : DbContext
    {
        public webstoreEntities()
            : base("name=webstoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCategories> tblCategories { get; set; }
        public virtual DbSet<tblProducts> tblProducts { get; set; }
        public virtual DbSet<tblCountry> tblCountry { get; set; }
        public virtual DbSet<tblComunas> tblComunas { get; set; }
        public virtual DbSet<tblProvincias> tblProvincias { get; set; }
        public virtual DbSet<tblRegiones> tblRegiones { get; set; }
        public virtual DbSet<tblFamily> tblFamily { get; set; }
        public virtual DbSet<tblModel> tblModel { get; set; }
        public virtual DbSet<tblModelDetail> tblModelDetail { get; set; }
        public virtual DbSet<tblCategoryRelation> tblCategoryRelation { get; set; }
        public virtual DbSet<tblBrand> tblBrand { get; set; }
        public virtual DbSet<tblOffert> tblOffert { get; set; }
        public virtual DbSet<tblOffertTime> tblOffertTime { get; set; }
        public virtual DbSet<tblImg> tblImg { get; set; }
        public virtual DbSet<tblRelBrand> tblRelBrand { get; set; }
        public virtual DbSet<tblFicha> tblFicha { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
        public virtual DbSet<tblAddresses> tblAddresses { get; set; }
        public virtual DbSet<tblAddressesDet> tblAddressesDet { get; set; }
        public virtual DbSet<tblQuotingQue> tblQuotingQue { get; set; }
        public virtual DbSet<tblQuotingQueDet> tblQuotingQueDet { get; set; }
        public virtual DbSet<tblProjects> tblProjects { get; set; }
        public virtual DbSet<tblAnswers> tblAnswers { get; set; }
        public virtual DbSet<tblQuestions> tblQuestions { get; set; }
    }
}
