//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webstoreEntities : DbContext
    {
        public webstoreEntities()
            : base("name=webstoreEntities")
        {
            Database.Connection.ConnectionString = Database.Connection.ConnectionString.Replace("XXXXX", "Softland2014");
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCategories> tblCategories { get; set; }
        public virtual DbSet<tblProducts> tblProducts { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
        public virtual DbSet<tblCountry> tblCountry { get; set; }
        public virtual DbSet<tblComunas> tblComunas { get; set; }
        public virtual DbSet<tblProvincias> tblProvincias { get; set; }
        public virtual DbSet<tblRegiones> tblRegiones { get; set; }
    }
}
