//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectropEntities : DbContext
    {
        public ElectropEntities()
            : base("name=ElectropEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<iw_gmovi> iw_gmovi { get; set; }
        public virtual DbSet<iw_gsaen> iw_gsaen { get; set; }
        public virtual DbSet<iw_tgrsubgr> iw_tgrsubgr { get; set; }
        public virtual DbSet<iw_tgrupo> iw_tgrupo { get; set; }
        public virtual DbSet<iw_tlispre> iw_tlispre { get; set; }
        public virtual DbSet<iw_tlpregrsubgr> iw_tlpregrsubgr { get; set; }
        public virtual DbSet<iw_tlprprod> iw_tlprprod { get; set; }
        public virtual DbSet<iw_tprod> iw_tprod { get; set; }
        public virtual DbSet<iw_tsubgr> iw_tsubgr { get; set; }
    }
}
