//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iw_gmovi
    {
        public string Tipo { get; set; }
        public int NroInt { get; set; }
        public int Linea { get; set; }
        public string CodProd { get; set; }
        public string CodBode { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> CantIngresada { get; set; }
        public Nullable<double> CantDespachada { get; set; }
        public Nullable<double> CantFacturada { get; set; }
        public Nullable<double> PreUniMB { get; set; }
        public Nullable<double> PreUniMVta { get; set; }
        public Nullable<double> PreUniMOrig { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<double> PorcDescMov01 { get; set; }
        public Nullable<double> DescMov01 { get; set; }
        public Nullable<double> PorcDescMov02 { get; set; }
        public Nullable<double> DescMov02 { get; set; }
        public Nullable<double> PorcDescMov03 { get; set; }
        public Nullable<double> DescMov03 { get; set; }
        public Nullable<double> PorcDescMov04 { get; set; }
        public Nullable<double> DescMov04 { get; set; }
        public Nullable<double> PorcDescMov05 { get; set; }
        public Nullable<double> DescMov05 { get; set; }
        public Nullable<double> TotalDescMov { get; set; }
        public Nullable<double> Equivalencia { get; set; }
        public Nullable<int> Actualizado { get; set; }
        public Nullable<double> TotLinea { get; set; }
        public string DetProd { get; set; }
        public Nullable<int> nvCorrela { get; set; }
        public string Partida { get; set; }
        public string Pieza { get; set; }
        public Nullable<System.DateTime> FechaVencto { get; set; }
        public string Ubicacion { get; set; }
        public string TipoOrigen { get; set; }
        public string TipoDestino { get; set; }
        public string AuxTipo { get; set; }
        public string CodAux { get; set; }
        public string CodiCC { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> ocCorrela { get; set; }
        public string KIT { get; set; }
        public Nullable<int> MarcaWG { get; set; }
        public Nullable<int> ImpresaOk { get; set; }
        public string CuentaConsumo { get; set; }
        public Nullable<int> CodPromocion { get; set; }
        public string CodUMed { get; set; }
        public Nullable<double> CantFactUVta { get; set; }
        public Nullable<double> CantDespUVta { get; set; }
        public Nullable<int> NumTrab { get; set; }
        public string CodProOF { get; set; }
        public Nullable<double> Recargo { get; set; }
        public Nullable<double> TotalDescMovBoleta { get; set; }
        public Nullable<double> PreUniBoleta { get; set; }
        public Nullable<double> TotalBoleta { get; set; }
        public Nullable<double> SolicitudMT { get; set; }
        public Nullable<double> NroLineaMT { get; set; }
        public Nullable<double> PorcRecMov01 { get; set; }
        public Nullable<double> RecMov01 { get; set; }
        public int NVCorrelaOC { get; set; }
    
        public virtual iw_tprod iw_tprod { get; set; }
    }
}
