//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iw_gsaen
    {
        public string Tipo { get; set; }
        public int NroInt { get; set; }
        public string CodBode { get; set; }
        public string CodCaja { get; set; }
        public Nullable<decimal> Folio { get; set; }
        public string Concepto { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaVenc { get; set; }
        public string Glosa { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<decimal> Factura { get; set; }
        public string AuxTipo { get; set; }
        public string CodAux { get; set; }
        public string CodiCC { get; set; }
        public string CodBod { get; set; }
        public Nullable<decimal> AuxGuiaNum { get; set; }
        public Nullable<System.DateTime> AuxGuiaFec { get; set; }
        public Nullable<decimal> AuxDocNum { get; set; }
        public Nullable<System.DateTime> AuxDocfec { get; set; }
        public string CodLugarDesp { get; set; }
        public string CodListaPrecio { get; set; }
        public string CodReserva { get; set; }
        public string CodVendedor { get; set; }
        public string CodMoneda { get; set; }
        public Nullable<double> Equivalencia { get; set; }
        public string Patente { get; set; }
        public string RetiradoPor { get; set; }
        public string Usuario { get; set; }
        public Nullable<double> NetoAfecto { get; set; }
        public Nullable<double> NetoExento { get; set; }
        public Nullable<double> IVA { get; set; }
        public Nullable<double> PorcDesc01 { get; set; }
        public Nullable<double> Descto01 { get; set; }
        public Nullable<double> PorcDesc02 { get; set; }
        public Nullable<double> Descto02 { get; set; }
        public Nullable<double> PorcDesc03 { get; set; }
        public Nullable<double> Descto03 { get; set; }
        public Nullable<double> PorcDesc04 { get; set; }
        public Nullable<double> Descto04 { get; set; }
        public Nullable<double> PorcDesc05 { get; set; }
        public Nullable<double> Descto05 { get; set; }
        public Nullable<double> TotalDesc { get; set; }
        public Nullable<double> Flete { get; set; }
        public Nullable<double> Embalaje { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> StockActualizado { get; set; }
        public Nullable<int> EnMantencion { get; set; }
        public string Cuenta { get; set; }
        public string CentroDeCosto { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public string CondPago { get; set; }
        public Nullable<int> ContabVenta { get; set; }
        public Nullable<int> ContabCosto { get; set; }
        public Nullable<int> ContDespPend { get; set; }
        public Nullable<int> ContConsumo { get; set; }
        public Nullable<int> ContVtaComp { get; set; }
        public string SolicitadoPor { get; set; }
        public string DespachadoPor { get; set; }
        public string NomAux { get; set; }
        public string RutAux { get; set; }
        public string ComAux { get; set; }
        public string CiuAux { get; set; }
        public string PaiAux { get; set; }
        public string DirAux { get; set; }
        public string FonAux { get; set; }
        public string FaxAux { get; set; }
        public string ComDch { get; set; }
        public string CiuDch { get; set; }
        public string PaiDch { get; set; }
        public string AtDch { get; set; }
        public string DirDch { get; set; }
        public string Sistema { get; set; }
        public string Proceso { get; set; }
        public Nullable<int> nvnumero { get; set; }
        public Nullable<int> ContabPago { get; set; }
        public Nullable<decimal> NumGuiaTrasp { get; set; }
        public Nullable<int> FueExportado { get; set; }
        public string Id_Paquete { get; set; }
        public Nullable<int> NroVale { get; set; }
        public string CanCod { get; set; }
        public Nullable<int> esDevolucion { get; set; }
        public string CWCpbAno { get; set; }
        public string CWCpbNum { get; set; }
        public string SubTipoDocto { get; set; }
        public Nullable<int> MarcaWG { get; set; }
        public string CpbAnoDespP { get; set; }
        public string CpbNumDespP { get; set; }
        public string CpbAnoPagos { get; set; }
        public string CpbNumPagos { get; set; }
        public string Cod_Distrib { get; set; }
        public string Nom_Distrib { get; set; }
        public Nullable<System.DateTime> FecHoraCreacion { get; set; }
        public Nullable<int> ListaMayorista { get; set; }
        public Nullable<int> BoletaFiscal { get; set; }
        public Nullable<int> ImpresaOk { get; set; }
        public string CpbAnoVentas { get; set; }
        public string CpbNumVentas { get; set; }
        public string CpbAnoCostos { get; set; }
        public string CpbNumCostos { get; set; }
        public string CpbAnoConsumos { get; set; }
        public string CpbNumConsumos { get; set; }
        public Nullable<int> ContabenPW { get; set; }
        public string TtdCod { get; set; }
        public string RutSolicitante { get; set; }
        public string RutTransportista { get; set; }
        public string TipDocRef { get; set; }
        public string SubTipDocRef { get; set; }
        public Nullable<int> DescLisPreenMov { get; set; }
        public Nullable<int> MotivoNCND { get; set; }
        public Nullable<double> CorrelativoAprobacion { get; set; }
        public string CpbAnoCompras { get; set; }
        public string CpbNumCompras { get; set; }
        public Nullable<int> DTE_SiiTDoc { get; set; }
        public Nullable<int> ContabenCW { get; set; }
        public Nullable<double> FactorCostoImportacion { get; set; }
        public string CodConvenio { get; set; }
        public Nullable<System.DateTime> FechaEmisConv { get; set; }
        public Nullable<int> TipoDespacho { get; set; }
        public Nullable<double> TotalDescBoleta { get; set; }
        public string CpbAnoCostosIFRS { get; set; }
        public string CpbNumCostosIFRS { get; set; }
        public string CpbAnoConsumosIFRS { get; set; }
        public string CpbNumConsumosIFRS { get; set; }
        public string CpbAnoComprasIFRS { get; set; }
        public string CpbNumComprasIFRS { get; set; }
        public string OtroRUT { get; set; }
        public string DondeDice { get; set; }
        public string DebeDecir { get; set; }
        public Nullable<int> TipoServicioSII { get; set; }
        public string CpbAnoTomaInv { get; set; }
        public string CpbNumTomaInv { get; set; }
        public Nullable<System.DateTime> FecHoraCreacionVW { get; set; }
        public Nullable<int> NroIntDctoRefAut { get; set; }
        public string TipoDctoRefAut { get; set; }
        public double PorcCredEmpConst { get; set; }
        public double DescCredEmpConst { get; set; }
        public int PagoConTarjeta { get; set; }
        public string IDLectorTarjeta { get; set; }
        public Nullable<double> NetoAfectoLF { get; set; }
        public Nullable<double> NetoExentoLF { get; set; }
        public Nullable<double> IVALF { get; set; }
        public Nullable<double> TotalLF { get; set; }
        public Nullable<System.DateTime> FechaIniLF { get; set; }
        public Nullable<System.DateTime> FechaFinLF { get; set; }
        public Nullable<int> NroPicking { get; set; }
        public Nullable<double> ComprobantePago { get; set; }
        public string CodLugarDocto { get; set; }
        public int TipoTrans { get; set; }
        public int FmaPago { get; set; }
        public string NroEmbarque { get; set; }
        public int EsImportacion { get; set; }
        public string CodAuxMandante { get; set; }
        public string NomContacto { get; set; }
    }
}
