//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iw_tlpregrsubgr
    {
        public string CodLista { get; set; }
        public string Tipo { get; set; }
        public string CodGrSubGr { get; set; }
        public Nullable<double> ValorPct { get; set; }
    }
}
