//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iw_tlispre
    {
        public string CodLista { get; set; }
        public string DesLista { get; set; }
        public string TipoLista { get; set; }
        public Nullable<System.DateTime> FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public Nullable<int> TipoPrecios { get; set; }
        public Nullable<int> EsPorcentaje { get; set; }
        public Nullable<int> EsPctUnico { get; set; }
        public Nullable<double> Porcentaje { get; set; }
        public Nullable<int> Contiene { get; set; }
        public string CodGrupo { get; set; }
        public int TipoCal { get; set; }
        public double PorCosPro { get; set; }
        public Nullable<int> TipoUniMed { get; set; }
        public Nullable<int> ManejaUM { get; set; }
    }
}
