//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iw_tprod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public iw_tprod()
        {
            this.iw_gmovi = new HashSet<iw_gmovi>();
        }
    
        public string CodProd { get; set; }
        public string DesProd { get; set; }
        public string DesProd2 { get; set; }
        public string CodRapido { get; set; }
        public string CodBarra { get; set; }
        public string CodUMed { get; set; }
        public Nullable<int> Origen { get; set; }
        public string CodMonOrig { get; set; }
        public string CodGrupo { get; set; }
        public string CodSubGr { get; set; }
        public string CodCateg { get; set; }
        public string CodMonPVta { get; set; }
        public Nullable<double> PrecioVta { get; set; }
        public Nullable<double> PrecioBol { get; set; }
        public Nullable<int> FichaTec { get; set; }
        public Nullable<int> EsConfig { get; set; }
        public Nullable<double> FactorConfig { get; set; }
        public Nullable<int> Impuesto { get; set; }
        public Nullable<int> Inventariable { get; set; }
        public Nullable<int> EsSerie { get; set; }
        public Nullable<int> EsTallaColor { get; set; }
        public Nullable<int> EsPartida { get; set; }
        public Nullable<int> EsCaducidad { get; set; }
        public Nullable<int> EsPieza { get; set; }
        public Nullable<int> CantPieza { get; set; }
        public Nullable<double> PesoKgs { get; set; }
        public string CtaActivo { get; set; }
        public string CtaVentas { get; set; }
        public string CtaGastos { get; set; }
        public string CtaCosto { get; set; }
        public Nullable<System.DateTime> FecUltCom { get; set; }
        public Nullable<double> ValorUltCom { get; set; }
        public Nullable<double> CostoRep { get; set; }
        public Nullable<System.DateTime> FecCostoRep { get; set; }
        public Nullable<System.DateTime> FecCMonet { get; set; }
        public Nullable<double> ValorCMonet { get; set; }
        public Nullable<double> NivMin { get; set; }
        public Nullable<double> NivRep { get; set; }
        public Nullable<double> NivMax { get; set; }
        public Nullable<int> Inamovible { get; set; }
        public Nullable<int> ManejaDim { get; set; }
        public Nullable<double> Ancho { get; set; }
        public Nullable<int> esUbicPar { get; set; }
        public string CtaDevolucion { get; set; }
        public string TipProd { get; set; }
        public Nullable<int> esParaVenta { get; set; }
        public Nullable<int> esParaCompra { get; set; }
        public Nullable<int> EsTalla { get; set; }
        public Nullable<int> EsColor { get; set; }
        public string MetodoCosteo { get; set; }
        public string CodUMedVta1 { get; set; }
        public Nullable<double> EquivUMVta1 { get; set; }
        public Nullable<double> PrecioVtaUM1 { get; set; }
        public Nullable<double> PrecioBolUM1 { get; set; }
        public string CodUMedVta2 { get; set; }
        public Nullable<double> EquivUMVta2 { get; set; }
        public Nullable<double> PrecioVtaUM2 { get; set; }
        public Nullable<double> PrecioBolUM2 { get; set; }
        public Nullable<int> UMDefecto { get; set; }
        public Nullable<int> ManProdAnticipo { get; set; }
        public Nullable<int> ImprimeEnBoleta { get; set; }
        public int EsParaAutoservicio { get; set; }
        public int Inactivo { get; set; }
        public string Usuario { get; set; }
        public string Proceso { get; set; }
        public Nullable<System.DateTime> FechaUlMod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iw_gmovi> iw_gmovi { get; set; }
        public virtual iw_tgrupo iw_tgrupo { get; set; }
        public virtual iw_tsubgr iw_tsubgr { get; set; }
    }
}
