//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddresses
    {
        public int idAddress { get; set; }
        public string strCountry { get; set; }
        public string strCity { get; set; }
        public string strAddress { get; set; }
        public string strType { get; set; }
        public Nullable<int> intPostalCode { get; set; }
        public Nullable<int> refRegion { get; set; }
        public Nullable<int> refProvince { get; set; }
        public Nullable<int> refComuna { get; set; }
        public Nullable<int> refuser { get; set; }
        public Nullable<bool> boolDefault { get; set; }
    
        public virtual tblComunas tblComunas { get; set; }
        public virtual tblRegiones tblRegiones { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
