//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddressesDetForCart
    {
        public int idAddressDet { get; set; }
        public int refAddressForCart { get; set; }
        public string strName { get; set; }
        public string strLastName { get; set; }
        public int intPhone { get; set; }
        public string intId { get; set; }
    
        public virtual tblAddressesForCart tblAddressesForCart { get; set; }
    }
}
