//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddressesForCart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAddressesForCart()
        {
            this.tblAddressesDetForCart = new HashSet<tblAddressesDetForCart>();
        }
    
        public int idAddress { get; set; }
        public string strCountry { get; set; }
        public string strCity { get; set; }
        public string strAddress { get; set; }
        public string strAddressTwo { get; set; }
        public string strType { get; set; }
        public Nullable<int> intPostalCode { get; set; }
        public int refRegion { get; set; }
        public int refProvince { get; set; }
        public int refComuna { get; set; }
        public int refCart { get; set; }
        public bool boolShipping { get; set; }
        public bool boolBill { get; set; }
        public bool boolThird { get; set; }
        public int intShippingPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAddressesDetForCart> tblAddressesDetForCart { get; set; }
        public virtual tblCart tblCart { get; set; }
        public virtual tblComunas tblComunas { get; set; }
        public virtual tblProvincias tblProvincias { get; set; }
        public virtual tblRegiones tblRegiones { get; set; }
    }
}
