//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAnswers
    {
        public int idAnswered { get; set; }
        public string strAnswer { get; set; }
        public System.DateTime strDate { get; set; }
        public int refUser { get; set; }
        public int refQuestion { get; set; }
    
        public virtual tblQuestions tblQuestions { get; set; }
    }
}
