//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCartDet
    {
        public int IdCartDet { get; set; }
        public int refCart { get; set; }
        public string refProd { get; set; }
        public int intQuantity { get; set; }
        public int intPrice { get; set; }
        public int intDiscount { get; set; }
        public int intPriceDiscount { get; set; }
    
        public virtual tblCart tblCart { get; set; }
    }
}
