//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategoryRelation
    {
        public int idCategoryRelation { get; set; }
        public Nullable<int> refCategoryOne { get; set; }
        public Nullable<int> refCategoryTwo { get; set; }
        public Nullable<int> refCategoryThree { get; set; }
    
        public virtual tblCategories tblCategories { get; set; }
        public virtual tblCategories tblCategories1 { get; set; }
        public virtual tblCategories tblCategories2 { get; set; }
    }
}
