//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCategories()
        {
            this.tblProducts = new HashSet<tblProducts>();
            this.tblCategoryRelation = new HashSet<tblCategoryRelation>();
            this.tblCategoryRelation1 = new HashSet<tblCategoryRelation>();
            this.tblCategoryRelation2 = new HashSet<tblCategoryRelation>();
        }
    
        public int idCategoria { get; set; }
        public string strNombre { get; set; }
        public Nullable<bool> intActivo { get; set; }
        public Nullable<int> intOrder { get; set; }
        public Nullable<int> refFamily { get; set; }
        public string strSeo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProducts> tblProducts { get; set; }
        public virtual tblFamily tblFamily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCategoryRelation> tblCategoryRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCategoryRelation> tblCategoryRelation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCategoryRelation> tblCategoryRelation2 { get; set; }
    }
}
