//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCompany()
        {
            this.tblRelCompanyUser = new HashSet<tblRelCompanyUser>();
        }
    
        public int idCompany { get; set; }
        public string intId { get; set; }
        public string strName { get; set; }
        public string strActivity { get; set; }
        public int intPhone { get; set; }
        public int refRegion { get; set; }
        public int refProvince { get; set; }
        public int refComune { get; set; }
        public string strCity { get; set; }
        public string strAddress { get; set; }
    
        public virtual tblComunas tblComunas { get; set; }
        public virtual tblProvincias tblProvincias { get; set; }
        public virtual tblRegiones tblRegiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRelCompanyUser> tblRelCompanyUser { get; set; }
    }
}
