//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCountry
    {
        public string iso { get; set; }
        public string strName { get; set; }
        public string strPrintableName { get; set; }
        public string iso3 { get; set; }
        public short intNumCode { get; set; }
    }
}
