//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCart()
        {
            this.tblCartDet = new HashSet<tblCartDet>();
            this.tblAddressesForCart = new HashSet<tblAddressesForCart>();
        }
    
        public int IdCart { get; set; }
        public System.DateTime strDate { get; set; }
        public int intSubTotal { get; set; }
        public int intDiscount { get; set; }
        public int intTotalN { get; set; }
        public int intTaxe { get; set; }
        public int Total { get; set; }
        public string strPayMethod { get; set; }
        public string intOrder { get; set; }
        public bool boolPayed { get; set; }
        public bool boolConfimed { get; set; }
        public int refUser { get; set; }
        public int intDocument { get; set; }
    
        public virtual tblUsers tblUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCartDet> tblCartDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAddressesForCart> tblAddressesForCart { get; set; }
    }
}
