//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComunas
    {
        public int idComuna { get; set; }
        public string strNombre { get; set; }
        public int refProvincia { get; set; }
    
        public virtual tblProvincias tblProvincias { get; set; }
    }
}
