//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCategories()
        {
            this.tblProducts = new HashSet<tblProducts>();
            this.tblCategoryRelation = new HashSet<tblCategoryRelation>();
            this.tblCategoryRelation1 = new HashSet<tblCategoryRelation>();
            this.tblCategoryRelation2 = new HashSet<tblCategoryRelation>();
        }
    
        public int idCategoria { get; set; }
        public string strNombre { get; set; }
        public Nullable<bool> intActivo { get; set; }
        public Nullable<int> intOrder { get; set; }
        public Nullable<int> refFamily { get; set; }
        public string strSeo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProducts> tblProducts { get; set; }
        public virtual tblFamily tblFamily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCategoryRelation> tblCategoryRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCategoryRelation> tblCategoryRelation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCategoryRelation> tblCategoryRelation2 { get; set; }
    }
}
