//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategoryRelation
    {
        public int idCategoryRelation { get; set; }
        public Nullable<int> refCategoryOne { get; set; }
        public Nullable<int> refCategoryTwo { get; set; }
        public Nullable<int> refCategoryThree { get; set; }
    
        public virtual tblCategories tblCategories { get; set; }
        public virtual tblCategories tblCategories1 { get; set; }
        public virtual tblCategories tblCategories2 { get; set; }
    }
}
