//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFicha
    {
        public int idFicha { get; set; }
        public Nullable<int> strPotencia { get; set; }
        public Nullable<int> intColorTemp { get; set; }
        public Nullable<int> intLumWatts { get; set; }
        public string strLifespan { get; set; }
        public string intVoltage { get; set; }
        public Nullable<decimal> intWeight { get; set; }
        public string strLHW { get; set; }
        public string strCertification { get; set; }
        public Nullable<int> intIp { get; set; }
        public Nullable<int> intIk { get; set; }
        public string intLightAngle { get; set; }
        public string strLightType { get; set; }
        public string strSolarPanel { get; set; }
        public string strBatery { get; set; }
        public Nullable<bool> intPir { get; set; }
        public string strWarranty { get; set; }
        public string strAutonomy { get; set; }
        public string strColor { get; set; }
        public string strInstalation { get; set; }
        public Nullable<int> intAmpers { get; set; }
        public Nullable<decimal> intPF { get; set; }
        public string strSocket { get; set; }
        public Nullable<int> intCRI { get; set; }
        public string strPoles { get; set; }
        public Nullable<int> intModule { get; set; }
        public string strBody { get; set; }
        public string strBodyCovert { get; set; }
        public Nullable<int> intDiameter { get; set; }
        public string strType { get; set; }
        public string strCountry { get; set; }
        public string intWorkTemp { get; set; }
        public Nullable<int> intCircuitBreakTemp { get; set; }
        public string strInclude { get; set; }
        public string strNoInclude { get; set; }
        public Nullable<bool> intNew { get; set; }
        public string refCodProd { get; set; }
        public bool strSec { get; set; }
        public bool strDs43 { get; set; }
        public bool strFicha { get; set; }
        public string strFrequency { get; set; }
        public string strBrand { get; set; }
    }
}
