//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistoryDet
    {
        public int IdHistoryDet { get; set; }
        public Nullable<int> refHistory { get; set; }
        public Nullable<int> refProduct { get; set; }
    
        public virtual tblHistory tblHistory { get; set; }
        public virtual tblProducts tblProducts { get; set; }
    }
}
