//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblModelDetail
    {
        public int idModelDetail { get; set; }
        public string strName { get; set; }
        public Nullable<int> intMain { get; set; }
        public Nullable<int> refModel { get; set; }
    
        public virtual tblModel tblModel { get; set; }
    }
}
