//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblModelDetail
    {
        public int idModelDetail { get; set; }
        public string strName { get; set; }
        public Nullable<int> intMain { get; set; }
        public Nullable<int> refModel { get; set; }
    
        public virtual tblModel tblModel { get; set; }
    }
}
