//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducts
    {
        public int idProdcuto { get; set; }
        public string strNombre { get; set; }
        public string strCodigo { get; set; }
        public decimal intPrecio { get; set; }
        public Nullable<int> refCategoria { get; set; }
    
        public virtual tblCategories tblCategories { get; set; }
    }
}
