//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjects
    {
        public int IdProject { get; set; }
        public string strTitle { get; set; }
        public string strDescription { get; set; }
        public int refImg { get; set; }
        public System.DateTime strDate { get; set; }
        public string strLocation { get; set; }
        public string strCategory { get; set; }
    
        public virtual tblImg tblImg { get; set; }
    }
}
