//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducts
    {
        public int idProdcuto { get; set; }
        public string strNombre { get; set; }
        public string strCodigo { get; set; }
        public decimal intPrecio { get; set; }
        public Nullable<int> refCategoria { get; set; }
        public Nullable<decimal> intPrecioTwo { get; set; }
        public string strImgOne { get; set; }
        public string strImgTwo { get; set; }
        public string strImgThree { get; set; }
        public Nullable<int> intStock { get; set; }
        public Nullable<bool> intNew { get; set; }
        public Nullable<bool> intActive { get; set; }
        public Nullable<int> refModel { get; set; }
        public Nullable<int> refCategoryRelation { get; set; }
        public Nullable<int> refBrand { get; set; }
    
        public virtual tblCategories tblCategories { get; set; }
        public virtual tblModel tblModel { get; set; }
        public virtual tblBrand tblBrand { get; set; }
    }
}
