//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProducts()
        {
            this.tblHistoryDet = new HashSet<tblHistoryDet>();
        }
    
        public int idProduct { get; set; }
        public string strCode { get; set; }
        public string strName { get; set; }
        public int intPrice { get; set; }
        public Nullable<int> intPriceTwo { get; set; }
        public Nullable<int> intStock { get; set; }
        public Nullable<bool> boolNew { get; set; }
        public Nullable<bool> boolActive { get; set; }
        public Nullable<int> refFamily { get; set; }
        public Nullable<int> refCategory { get; set; }
        public Nullable<int> refModel { get; set; }
        public Nullable<int> refCategoryRelation { get; set; }
        public Nullable<int> refBrand { get; set; }
        public Nullable<int> refFicha { get; set; }
        public Nullable<int> refOffert { get; set; }
        public Nullable<int> refOfferTime { get; set; }
        public Nullable<int> refImg { get; set; }
        public string strCodeS { get; set; }
    
        public virtual tblBrand tblBrand { get; set; }
        public virtual tblCategories tblCategories { get; set; }
        public virtual tblImg tblImg { get; set; }
        public virtual tblModel tblModel { get; set; }
        public virtual tblOffert tblOffert { get; set; }
        public virtual tblOffertTime tblOffertTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHistoryDet> tblHistoryDet { get; set; }
    }
}
