//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuestions()
        {
            this.tblAnswers = new HashSet<tblAnswers>();
        }
    
        public int idQuestion { get; set; }
        public string strQuestion { get; set; }
        public System.DateTime strDate { get; set; }
        public int refUser { get; set; }
        public string refProduct { get; set; }
        public bool boolAnswered { get; set; }
        public int intStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAnswers> tblAnswers { get; set; }
    }
}
