//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotingsDet
    {
        public int IdQuotingDet { get; set; }
        public int refQuoting { get; set; }
        public string refProduct { get; set; }
        public int intQuantity { get; set; }
    
        public virtual tblQuotings tblQuotings { get; set; }
    }
}
