//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuotings()
        {
            this.tblQuotingsDet = new HashSet<tblQuotingsDet>();
        }
    
        public int IdQuoting { get; set; }
        public string strName { get; set; }
        public string strLastname { get; set; }
        public string strEmail { get; set; }
        public int intPhone { get; set; }
        public System.DateTime strDate { get; set; }
        public string strComment { get; set; }
        public Nullable<int> refUser { get; set; }
    
        public virtual tblUsers tblUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotingsDet> tblQuotingsDet { get; set; }
    }
}
