//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotingQueDet
    {
        public int IdQuotingQueDet { get; set; }
        public int refQuotingQue { get; set; }
        public string refCodProd { get; set; }
        public int Quantity { get; set; }
    
        public virtual tblQuotingQue tblQuotingQue { get; set; }
    }
}
