//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRelBrand
    {
        public int idRelation { get; set; }
        public Nullable<int> refBrand { get; set; }
        public string refProd { get; set; }
    
        public virtual tblBrand tblBrand { get; set; }
    }
}
