//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRelCompanyUser
    {
        public int id { get; set; }
        public int refUser { get; set; }
        public int refCompany { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
