//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUsers()
        {
            this.tblAddresses = new HashSet<tblAddresses>();
            this.tblHistory = new HashSet<tblHistory>();
            this.tblQuotingQue = new HashSet<tblQuotingQue>();
            this.tblQuotings = new HashSet<tblQuotings>();
            this.tblRelCompanyUser = new HashSet<tblRelCompanyUser>();
            this.tblCartQue = new HashSet<tblCartQue>();
        }
    
        public int idUser { get; set; }
        public string intId { get; set; }
        public string strNames { get; set; }
        public string strLastNames { get; set; }
        public string strEmail { get; set; }
        public Nullable<int> intPhone { get; set; }
        public string strPassword { get; set; }
        public Nullable<System.DateTime> strRegistrationDate { get; set; }
        public Nullable<System.Guid> strVerificationCode { get; set; }
        public Nullable<int> intLevel { get; set; }
        public Nullable<bool> boolValidate { get; set; }
        public string strRecoveryCode { get; set; }
        public Nullable<System.DateTime> timeRecoveryCode { get; set; }
        public string strProvider { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAddresses> tblAddresses { get; set; }
        public virtual tblAvatars tblAvatars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHistory> tblHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotingQue> tblQuotingQue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuotings> tblQuotings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRelCompanyUser> tblRelCompanyUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCartQue> tblCartQue { get; set; }
    }
}
