//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsers
    {
        public int idUser { get; set; }
        public string strNames { get; set; }
        public string strLastNames { get; set; }
        public string strEmail { get; set; }
        public string strPassword { get; set; }
        public Nullable<System.Guid> strVerificationCode { get; set; }
        public Nullable<int> intLevel { get; set; }
        public Nullable<bool> boolValidate { get; set; }
    }
}
