//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Categories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Categories() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebStore.Resources.Categories", typeof(Categories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        public static string Accessories {
            get {
                return ResourceManager.GetString("Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapters.
        /// </summary>
        public static string Adapters {
            get {
                return ResourceManager.GetString("Adapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atex.
        /// </summary>
        public static string Atex {
            get {
                return ResourceManager.GetString("Atex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes and Boards.
        /// </summary>
        public static string BoxBoards {
            get {
                return ResourceManager.GetString("BoxBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakers.
        /// </summary>
        public static string Breaker {
            get {
                return ResourceManager.GetString("Breaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable Glands.
        /// </summary>
        public static string CableGland {
            get {
                return ResourceManager.GetString("CableGland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Cables.
        /// </summary>
        public static string Cables {
            get {
                return ResourceManager.GetString("Cables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable Ties.
        /// </summary>
        public static string CableTie {
            get {
                return ResourceManager.GetString("CableTie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control and Command.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differentials.
        /// </summary>
        public static string Differentials {
            get {
                return ResourceManager.GetString("Differentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimers.
        /// </summary>
        public static string Dimers {
            get {
                return ResourceManager.GetString("Dimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributors.
        /// </summary>
        public static string Distributors {
            get {
                return ResourceManager.GetString("Distributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Materials.
        /// </summary>
        public static string ElectricMaterials {
            get {
                return ResourceManager.GetString("ElectricMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Canalization.
        /// </summary>
        public static string ElectricTubes {
            get {
                return ResourceManager.GetString("ElectricTubes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency.
        /// </summary>
        public static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        public static string Extensions {
            get {
                return ResourceManager.GetString("Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faena Bords.
        /// </summary>
        public static string Faena {
            get {
                return ResourceManager.GetString("Faena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female Plugs.
        /// </summary>
        public static string FemalePlugs {
            get {
                return ResourceManager.GetString("FemalePlugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber Tray.
        /// </summary>
        public static string FiberTray {
            get {
                return ResourceManager.GetString("FiberTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuses.
        /// </summary>
        public static string Fuses {
            get {
                return ResourceManager.GetString("Fuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galvanized Tray.
        /// </summary>
        public static string GalvaTray {
            get {
                return ResourceManager.GetString("GalvaTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden.
        /// </summary>
        public static string Garden {
            get {
                return ResourceManager.GetString("Garden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoses.
        /// </summary>
        public static string Hose {
            get {
                return ResourceManager.GetString("Hose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial Female Plugs.
        /// </summary>
        public static string IndustrialFemale {
            get {
                return ResourceManager.GetString("IndustrialFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial Male Plugs.
        /// </summary>
        public static string IndustrialMale {
            get {
                return ResourceManager.GetString("IndustrialMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladders.
        /// </summary>
        public static string Ladders {
            get {
                return ResourceManager.GetString("Ladders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lights.
        /// </summary>
        public static string Lights {
            get {
                return ResourceManager.GetString("Lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male Plugs.
        /// </summary>
        public static string MalePlugs {
            get {
                return ResourceManager.GetString("MalePlugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel.
        /// </summary>
        public static string Parallel {
            get {
                return ResourceManager.GetString("Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plates.
        /// </summary>
        public static string Plates {
            get {
                return ResourceManager.GetString("Plates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugs and Adapters.
        /// </summary>
        public static string Plugs {
            get {
                return ResourceManager.GetString("Plugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamp Posts.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Points.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorative.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Buttons.
        /// </summary>
        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVC.
        /// </summary>
        public static string PVC {
            get {
                return ResourceManager.GetString("PVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q-DIN Boards.
        /// </summary>
        public static string QDIN {
            get {
                return ResourceManager.GetString("QDIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential.
        /// </summary>
        public static string Residential {
            get {
                return ResourceManager.GetString("Residential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tubes.
        /// </summary>
        public static string Tubes {
            get {
                return ResourceManager.GetString("Tubes", resourceCulture);
            }
        }
    }
}
