//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Categories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Categories() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebStore.Resources.Categories", typeof(Categories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explosive Atmospheres.
        /// </summary>
        public static string Atex {
            get {
                return ResourceManager.GetString("Atex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boards.
        /// </summary>
        public static string Boards {
            get {
                return ResourceManager.GetString("Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bottons.
        /// </summary>
        public static string Bottons {
            get {
                return ResourceManager.GetString("Bottons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Breakers, power points and dimmers.
        /// </summary>
        public static string BPD {
            get {
                return ResourceManager.GetString("BPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Breakers.
        /// </summary>
        public static string Breakers {
            get {
                return ResourceManager.GetString("Breakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cable press.
        /// </summary>
        public static string CablePress {
            get {
                return ResourceManager.GetString("CablePress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cables.
        /// </summary>
        public static string Cables {
            get {
                return ResourceManager.GetString("Cables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contactor and thermic rele.
        /// </summary>
        public static string ContactorRele {
            get {
                return ResourceManager.GetString("ContactorRele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control and command.
        /// </summary>
        public static string ControlCommand {
            get {
                return ResourceManager.GetString("ControlCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cordons.
        /// </summary>
        public static string Cordons {
            get {
                return ResourceManager.GetString("Cordons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Differentials.
        /// </summary>
        public static string Differentials {
            get {
                return ResourceManager.GetString("Differentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distribution Boxes.
        /// </summary>
        public static string DistributionBoxes {
            get {
                return ResourceManager.GetString("DistributionBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distributors.
        /// </summary>
        public static string Distributors {
            get {
                return ResourceManager.GetString("Distributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electrical canalization.
        /// </summary>
        public static string ElectricCanalization {
            get {
                return ResourceManager.GetString("ElectricCanalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electrical conductor.
        /// </summary>
        public static string ElectricConductor {
            get {
                return ResourceManager.GetString("ElectricConductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electrical hardware store.
        /// </summary>
        public static string ElectricHardware {
            get {
                return ResourceManager.GetString("ElectricHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emergency.
        /// </summary>
        public static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faena boards.
        /// </summary>
        public static string Faena {
            get {
                return ResourceManager.GetString("Faena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Females.
        /// </summary>
        public static string Females {
            get {
                return ResourceManager.GetString("Females", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frequency variator.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Garden.
        /// </summary>
        public static string Garden {
            get {
                return ResourceManager.GetString("Garden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hermetics.
        /// </summary>
        public static string Hermetics {
            get {
                return ResourceManager.GetString("Hermetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home lights.
        /// </summary>
        public static string HomeLights {
            get {
                return ResourceManager.GetString("HomeLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Industrial.
        /// </summary>
        public static string Industrial {
            get {
                return ResourceManager.GetString("Industrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Industrial lights.
        /// </summary>
        public static string IndustryLights {
            get {
                return ResourceManager.GetString("IndustryLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Industrial plugs.
        /// </summary>
        public static string IndustryPlugs {
            get {
                return ResourceManager.GetString("IndustryPlugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ladders.
        /// </summary>
        public static string Ladders {
            get {
                return ResourceManager.GetString("Ladders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lightbulbs and tubes.
        /// </summary>
        public static string LightbulbsTubes {
            get {
                return ResourceManager.GetString("LightbulbsTubes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Males.
        /// </summary>
        public static string Males {
            get {
                return ResourceManager.GetString("Males", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motor safer.
        /// </summary>
        public static string Motor {
            get {
                return ResourceManager.GetString("Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plates.
        /// </summary>
        public static string Plates {
            get {
                return ResourceManager.GetString("Plates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posts.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pushes.
        /// </summary>
        public static string Pushes {
            get {
                return ResourceManager.GetString("Pushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PVC.
        /// </summary>
        public static string PVC {
            get {
                return ResourceManager.GetString("PVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Q-din boards.
        /// </summary>
        public static string Qdin {
            get {
                return ResourceManager.GetString("Qdin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Residential.
        /// </summary>
        public static string Residential {
            get {
                return ResourceManager.GetString("Residential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soft-breaker.
        /// </summary>
        public static string SoftBreaker {
            get {
                return ResourceManager.GetString("SoftBreaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stadium.
        /// </summary>
        public static string Stadium {
            get {
                return ResourceManager.GetString("Stadium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stoma press.
        /// </summary>
        public static string StomaPress {
            get {
                return ResourceManager.GetString("StomaPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solar.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trays.
        /// </summary>
        public static string Trays {
            get {
                return ResourceManager.GetString("Trays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tubes.
        /// </summary>
        public static string Tubes {
            get {
                return ResourceManager.GetString("Tubes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wires.
        /// </summary>
        public static string Wires {
            get {
                return ResourceManager.GetString("Wires", resourceCulture);
            }
        }
    }
}
