//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ficha {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ficha() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebStore.Resources.Ficha", typeof(Ficha).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ampers.
        /// </summary>
        public static string Ampers {
            get {
                return ResourceManager.GetString("Ampers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autonomy.
        /// </summary>
        public static string Autonomy {
            get {
                return ResourceManager.GetString("Autonomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Batery.
        /// </summary>
        public static string Batery {
            get {
                return ResourceManager.GetString("Batery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Body covert.
        /// </summary>
        public static string BodyCovert {
            get {
                return ResourceManager.GetString("BodyCovert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certifications.
        /// </summary>
        public static string Certification {
            get {
                return ResourceManager.GetString("Certification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Circuit break temperature.
        /// </summary>
        public static string CircuitTemp {
            get {
                return ResourceManager.GetString("CircuitTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temperature Light Color (CCT°).
        /// </summary>
        public static string ColorLight {
            get {
                return ResourceManager.GetString("ColorLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color rendering index.
        /// </summary>
        public static string CRI {
            get {
                return ResourceManager.GetString("CRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diameter.
        /// </summary>
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download Ds43 certification.
        /// </summary>
        public static string Ds43 {
            get {
                return ResourceManager.GetString("Ds43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impact protection.
        /// </summary>
        public static string IK {
            get {
                return ResourceManager.GetString("IK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Include.
        /// </summary>
        public static string Include {
            get {
                return ResourceManager.GetString("Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalation.
        /// </summary>
        public static string Instalation {
            get {
                return ResourceManager.GetString("Instalation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingress protection.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dimensions.
        /// </summary>
        public static string LHW {
            get {
                return ResourceManager.GetString("LHW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Life span.
        /// </summary>
        public static string Life {
            get {
                return ResourceManager.GetString("Life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Light angle.
        /// </summary>
        public static string LightAngle {
            get {
                return ResourceManager.GetString("LightAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Light Type.
        /// </summary>
        public static string LightType {
            get {
                return ResourceManager.GetString("LightType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lummes/W.
        /// </summary>
        public static string LumWatts {
            get {
                return ResourceManager.GetString("LumWatts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modules.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No include.
        /// </summary>
        public static string NoInclude {
            get {
                return ResourceManager.GetString("NoInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Power factor.
        /// </summary>
        public static string PF {
            get {
                return ResourceManager.GetString("PF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movements sensor.
        /// </summary>
        public static string Pir {
            get {
                return ResourceManager.GetString("Pir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poles.
        /// </summary>
        public static string Poles {
            get {
                return ResourceManager.GetString("Poles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Power.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download Sec certification.
        /// </summary>
        public static string Sec {
            get {
                return ResourceManager.GetString("Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download tecnical sheet.
        /// </summary>
        public static string Sheet {
            get {
                return ResourceManager.GetString("Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Socket.
        /// </summary>
        public static string Socket {
            get {
                return ResourceManager.GetString("Socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solar Panel.
        /// </summary>
        public static string SolarPanel {
            get {
                return ResourceManager.GetString("SolarPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Voltage.
        /// </summary>
        public static string V {
            get {
                return ResourceManager.GetString("V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warranty.
        /// </summary>
        public static string Warranty {
            get {
                return ResourceManager.GetString("Warranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work temperature.
        /// </summary>
        public static string WorkTemp {
            get {
                return ResourceManager.GetString("WorkTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
