//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Placeholder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Placeholder() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebStore.Resources.Placeholder", typeof(Placeholder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose City.
        /// </summary>
        public static string CCity {
            get {
                return ResourceManager.GetString("CCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose Country.
        /// </summary>
        public static string CCountry {
            get {
                return ResourceManager.GetString("CCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comune/Sector.
        /// </summary>
        public static string Comune {
            get {
                return ResourceManager.GetString("Comune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How urgent is your issue?.
        /// </summary>
        public static string CPriority {
            get {
                return ResourceManager.GetString("CPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose type.
        /// </summary>
        public static string CType {
            get {
                return ResourceManager.GetString("CType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cupon Code.
        /// </summary>
        public static string Cupon {
            get {
                return ResourceManager.GetString("Cupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document type.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your e-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a House/Apartment.
        /// </summary>
        public static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUT/ID XX.XXX.XXX-X.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Number.
        /// </summary>
        public static string IdNum {
            get {
                return ResourceManager.GetString("IdNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info Inquiry.
        /// </summary>
        public static string IType {
            get {
                return ResourceManager.GetString("IType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Names.
        /// </summary>
        public static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write your message here....
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Names.
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone +56 9 XXXX XXXX.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zip Code.
        /// </summary>
        public static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State/Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm you password.
        /// </summary>
        public static string RePassword {
            get {
                return ResourceManager.GetString("RePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partner Request.
        /// </summary>
        public static string RType {
            get {
                return ResourceManager.GetString("RType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Same as billing address.
        /// </summary>
        public static string SameAddress {
            get {
                return ResourceManager.GetString("SameAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is the same person of the bill?.
        /// </summary>
        public static string SamePerson {
            get {
                return ResourceManager.GetString("SamePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shipping to address.
        /// </summary>
        public static string Shipping {
            get {
                return ResourceManager.GetString("Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State/Province/Region.
        /// </summary>
        public static string StateRegion {
            get {
                return ResourceManager.GetString("StateRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pick up in store.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your e-mail.
        /// </summary>
        public static string Subs {
            get {
                return ResourceManager.GetString("Subs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complain.
        /// </summary>
        public static string TypeC {
            get {
                return ResourceManager.GetString("TypeC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Urgent.
        /// </summary>
        public static string Urgent {
            get {
                return ResourceManager.GetString("Urgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write a description....
        /// </summary>
        public static string WDescription {
            get {
                return ResourceManager.GetString("WDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Website Problem.
        /// </summary>
        public static string WType {
            get {
                return ResourceManager.GetString("WType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your Name.
        /// </summary>
        public static string YouName {
            get {
                return ResourceManager.GetString("YouName", resourceCulture);
            }
        }
    }
}
