//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebStore.Resources.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;/Scripts/Countdown/Countdown.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string CountdownJs {
            get {
                return ResourceManager.GetString("CountdownJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;/Scripts/Custom-validators.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string CustomValidator {
            get {
                return ResourceManager.GetString("CustomValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;/Scripts/jquery.interactive_3d.js&quot; async&gt;&lt;/script&gt;.
        /// </summary>
        public static string Interactive3dJs {
            get {
                return ResourceManager.GetString("Interactive3dJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js&quot; async&gt;&lt;/script&gt;.
        /// </summary>
        public static string Isotope {
            get {
                return ResourceManager.GetString("Isotope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js&quot; integrity=&quot;sha256-u7MY6EG5ass8JhTuxBek18r5YG6pllB9zLqE4vZyTn4=&quot; crossorigin=&quot;anonymous&quot; async&gt;&lt;/script&gt;.
        /// </summary>
        public static string JqueryMask {
            get {
                return ResourceManager.GetString("JqueryMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;https://code.jquery.com/ui/1.12.1/jquery-ui.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string JqueryUi {
            get {
                return ResourceManager.GetString("JqueryUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;https://rawgithub.com/hayageek/jquery-upload-file/master/js/jquery.uploadfile.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string JqueryUpload {
            get {
                return ResourceManager.GetString("JqueryUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string JqueryValidate {
            get {
                return ResourceManager.GetString("JqueryValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/additional-methods.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string JqueryValidateMethods {
            get {
                return ResourceManager.GetString("JqueryValidateMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;/Scripts/jquery.validate.unobtrusive.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string JqueryValidateUnobtrousive {
            get {
                return ResourceManager.GetString("JqueryValidateUnobtrousive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/mouse0270-bootstrap-notify/3.1.7/bootstrap-notify.js&quot; integrity=&quot;sha256-ZfyZUBGHlJunePNMsBqgGX3xHMv4kaCZ5Hj+8Txwd9c=&quot; crossorigin=&quot;anonymous&quot; async&gt;&lt;/script&gt;.
        /// </summary>
        public static string NotifyJs {
            get {
                return ResourceManager.GetString("NotifyJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/14.0.2/nouislider.min.js&quot; integrity=&quot;sha256-VG+4f1Hm2q4e+DTEOaiZKlWjJm5W4yqnXNvKkWBYA20=&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string NoUiSliderJs {
            get {
                return ResourceManager.GetString("NoUiSliderJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;/Scripts/OwlCarousel/owl.carousel.min.js&quot; async&gt;&lt;/script&gt;.
        /// </summary>
        public static string OwlCarousel {
            get {
                return ResourceManager.GetString("OwlCarousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;/Scripts/OwlCarousel/Carousels.min.js&quot; async&gt;&lt;/script&gt;.
        /// </summary>
        public static string OwlCarouselJs {
            get {
                return ResourceManager.GetString("OwlCarouselJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;/Scripts/OwlCarousel/owl.carousel2.thumbs.min.js&quot; async&gt;&lt;/script&gt;.
        /// </summary>
        public static string OwlCarouselThumbs {
            get {
                return ResourceManager.GetString("OwlCarouselThumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/paginationjs/2.1.4/pagination.min.js&quot; integrity=&quot;sha256-E+fw0vUbuPq4p3FWWtX7FzzlcMTe7hvrgZxOk8LPAh4=&quot; crossorigin=&quot;anonymous&quot; async&gt;&lt;/script&gt;.
        /// </summary>
        public static string PaginationJs {
            get {
                return ResourceManager.GetString("PaginationJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe.min.js&quot; integrity=&quot;sha256-ePwmChbbvXbsO02lbM3HoHbSHTHFAeChekF1xKJdleo=&quot; crossorigin=&quot;anonymous&quot; async&gt;&lt;/script&gt;.
        /// </summary>
        public static string PhotoSwipeJs {
            get {
                return ResourceManager.GetString("PhotoSwipeJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe-ui-default.min.js&quot; integrity=&quot;sha256-UKkzOn/w1mBxRmLLGrSeyB4e1xbrp4xylgAWb3M42pU=&quot; crossorigin=&quot;anonymous&quot; async&gt;&lt;/script&gt;.
        /// </summary>
        public static string PhotoSwipeUiJs {
            get {
                return ResourceManager.GetString("PhotoSwipeUiJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;/Scripts/jquery.steps.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string StepJs {
            get {
                return ResourceManager.GetString("StepJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;https://cdn.jsdelivr.net/npm/sweetalert2@7.26.12/dist/sweetalert2.all.min.js&quot; integrity=&quot;sha256-Y+WJP3jVjJgfw+/m2N5/GGUgxqXDCz7S3zstxj8pqng=&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string SweetAlert {
            get {
                return ResourceManager.GetString("SweetAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/wnumb/1.1.0/wNumb.min.js&quot; integrity=&quot;sha256-HT7c4lBipI1Hkl/uvUrU1HQx4WF3oQnSafPjgR9Cn8A=&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string wNumJs {
            get {
                return ResourceManager.GetString("wNumJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;/Scripts/Animation/wow.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string WowJs {
            get {
                return ResourceManager.GetString("WowJs", resourceCulture);
            }
        }
    }
}
