//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebStore.Resources.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;/Scripts/Countdown/Countdown.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string CountdownJs {
            get {
                return ResourceManager.GetString("CountdownJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;/Scripts/jquery.interactive_3d.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string Interactive3dJs {
            get {
                return ResourceManager.GetString("Interactive3dJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string Isotope {
            get {
                return ResourceManager.GetString("Isotope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js&quot; integrity=&quot;sha256-u7MY6EG5ass8JhTuxBek18r5YG6pllB9zLqE4vZyTn4=&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string JqueryMask {
            get {
                return ResourceManager.GetString("JqueryMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;https://code.jquery.com/ui/1.12.1/jquery-ui.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string JqueryUi {
            get {
                return ResourceManager.GetString("JqueryUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string JqueryValidate {
            get {
                return ResourceManager.GetString("JqueryValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/additional-methods.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string JqueryValidateMethods {
            get {
                return ResourceManager.GetString("JqueryValidateMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/mouse0270-bootstrap-notify/3.1.7/bootstrap-notify.js&quot; integrity=&quot;sha256-ZfyZUBGHlJunePNMsBqgGX3xHMv4kaCZ5Hj+8Txwd9c=&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string NotifyJs {
            get {
                return ResourceManager.GetString("NotifyJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;/Scripts/OwlCarousel/owl.carousel.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string OwlCarousel {
            get {
                return ResourceManager.GetString("OwlCarousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;/Scripts/OwlCarousel/Carousels.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string OwlCarouselJs {
            get {
                return ResourceManager.GetString("OwlCarouselJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;/Scripts/OwlCarousel/owl.carousel2.thumbs.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string OwlCarouselThumbs {
            get {
                return ResourceManager.GetString("OwlCarouselThumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/paginationjs/2.1.4/pagination.min.js&quot; integrity=&quot;sha256-E+fw0vUbuPq4p3FWWtX7FzzlcMTe7hvrgZxOk8LPAh4=&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string PaginationJs {
            get {
                return ResourceManager.GetString("PaginationJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe.min.js&quot; integrity=&quot;sha256-ePwmChbbvXbsO02lbM3HoHbSHTHFAeChekF1xKJdleo=&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string PhotoSwipeJs {
            get {
                return ResourceManager.GetString("PhotoSwipeJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.3/photoswipe-ui-default.min.js&quot; integrity=&quot;sha256-UKkzOn/w1mBxRmLLGrSeyB4e1xbrp4xylgAWb3M42pU=&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string PhotoSwipeUiJs {
            get {
                return ResourceManager.GetString("PhotoSwipeUiJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;/Scripts/jquery.steps.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string StepJs {
            get {
                return ResourceManager.GetString("StepJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;https://cdn.jsdelivr.net/npm/sweetalert2@7.26.12/dist/sweetalert2.all.min.js&quot; integrity=&quot;sha256-Y+WJP3jVjJgfw+/m2N5/GGUgxqXDCz7S3zstxj8pqng=&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string SweetAlert {
            get {
                return ResourceManager.GetString("SweetAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;script src=&quot;/Scripts/Animation/wow.min.js&quot;&gt;&lt;/script&gt;.
        /// </summary>
        public static string WowJs {
            get {
                return ResourceManager.GetString("WowJs", resourceCulture);
            }
        }
    }
}
