//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Seo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Seo() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebStore.Resources.Seo", typeof(Seo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a explosive-atmospheres.
        /// </summary>
        public static string Atex {
            get {
                return ResourceManager.GetString("Atex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a boards.
        /// </summary>
        public static string Boards {
            get {
                return ResourceManager.GetString("Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bottons.
        /// </summary>
        public static string Bottons {
            get {
                return ResourceManager.GetString("Bottons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a breakers-powerpoints-and-dimmers.
        /// </summary>
        public static string BPD {
            get {
                return ResourceManager.GetString("BPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a breakers.
        /// </summary>
        public static string Breakers {
            get {
                return ResourceManager.GetString("Breakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cables-press.
        /// </summary>
        public static string CablePress {
            get {
                return ResourceManager.GetString("CablePress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cables.
        /// </summary>
        public static string Cables {
            get {
                return ResourceManager.GetString("Cables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a contactor-and-thermic-rele.
        /// </summary>
        public static string ContactorRele {
            get {
                return ResourceManager.GetString("ContactorRele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a control-and-command.
        /// </summary>
        public static string ControlCommand {
            get {
                return ResourceManager.GetString("ControlCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cordons.
        /// </summary>
        public static string Cordons {
            get {
                return ResourceManager.GetString("Cordons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a differentials.
        /// </summary>
        public static string Differentials {
            get {
                return ResourceManager.GetString("Differentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a distribution-boxes.
        /// </summary>
        public static string DistributionBoxes {
            get {
                return ResourceManager.GetString("DistributionBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a distributors.
        /// </summary>
        public static string Distributors {
            get {
                return ResourceManager.GetString("Distributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a electrical-canalization.
        /// </summary>
        public static string ElectricCanalization {
            get {
                return ResourceManager.GetString("ElectricCanalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a electrical-conductor.
        /// </summary>
        public static string ElectricConductor {
            get {
                return ResourceManager.GetString("ElectricConductor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a electrical-hardware-store.
        /// </summary>
        public static string ElectricHardware {
            get {
                return ResourceManager.GetString("ElectricHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a emergency.
        /// </summary>
        public static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a faena-boards.
        /// </summary>
        public static string Faena {
            get {
                return ResourceManager.GetString("Faena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a females-plugs.
        /// </summary>
        public static string Females {
            get {
                return ResourceManager.GetString("Females", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a frequency-variator.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a garden.
        /// </summary>
        public static string Garden {
            get {
                return ResourceManager.GetString("Garden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hermetics.
        /// </summary>
        public static string Hermetics {
            get {
                return ResourceManager.GetString("Hermetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a home-lights.
        /// </summary>
        public static string HomeLights {
            get {
                return ResourceManager.GetString("HomeLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a industrial.
        /// </summary>
        public static string Industrial {
            get {
                return ResourceManager.GetString("Industrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a industrial-lights.
        /// </summary>
        public static string IndustryLights {
            get {
                return ResourceManager.GetString("IndustryLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a industrial-plugs.
        /// </summary>
        public static string IndustryPlugs {
            get {
                return ResourceManager.GetString("IndustryPlugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ladders.
        /// </summary>
        public static string Ladders {
            get {
                return ResourceManager.GetString("Ladders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a lightbulbs-and-tubes.
        /// </summary>
        public static string LightbulbsTubes {
            get {
                return ResourceManager.GetString("LightbulbsTubes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a males-plugs.
        /// </summary>
        public static string Males {
            get {
                return ResourceManager.GetString("Males", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a motor-safer.
        /// </summary>
        public static string Motor {
            get {
                return ResourceManager.GetString("Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a plates.
        /// </summary>
        public static string Plates {
            get {
                return ResourceManager.GetString("Plates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a plugs-adapters.
        /// </summary>
        public static string PlugsAdapters {
            get {
                return ResourceManager.GetString("PlugsAdapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a posts.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a public.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pushes.
        /// </summary>
        public static string Pushes {
            get {
                return ResourceManager.GetString("Pushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pvc.
        /// </summary>
        public static string PVC {
            get {
                return ResourceManager.GetString("PVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a q-din-boards.
        /// </summary>
        public static string Qdin {
            get {
                return ResourceManager.GetString("Qdin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a residential.
        /// </summary>
        public static string Residential {
            get {
                return ResourceManager.GetString("Residential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a soft-breaker.
        /// </summary>
        public static string SoftBreaker {
            get {
                return ResourceManager.GetString("SoftBreaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a stadium.
        /// </summary>
        public static string Stadium {
            get {
                return ResourceManager.GetString("Stadium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a stoma-press.
        /// </summary>
        public static string StomaPress {
            get {
                return ResourceManager.GetString("StomaPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a solar.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a trays.
        /// </summary>
        public static string Trays {
            get {
                return ResourceManager.GetString("Trays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tubes.
        /// </summary>
        public static string Tubes {
            get {
                return ResourceManager.GetString("Tubes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a wires.
        /// </summary>
        public static string Wires {
            get {
                return ResourceManager.GetString("Wires", resourceCulture);
            }
        }
    }
}
